version: "3.8"
services:
  api:
    build: .
    ports:
      - 8000:8000
    networks:
      - app-network
    command: ./docker-entrypoint.sh

  db:
    image: postgres:alpine3.16
    restart: always
    networks:
      app-network:
        aliases:
          - postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1243
      POSTGRES_DB: bitlygo
    volumes:
      - bitlygo:/var/lib/postgres/data
volumes:
  bitlygo: 
    driver: local

networks:
  app-network:
    driver: bridge
